# Generated by Django 4.2.7 on 2025-08-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0016_alter_feedbackreaction_reaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedbackreaction',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='feedbackreaction',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='feedbackreaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='guestfeedbacksession',
            name='invitation',
        ),
        migrations.RemoveField(
            model_name='guestfeedbacksession',
            name='project',
        ),
        migrations.AlterModelOptions(
            name='feedbackmessage',
            options={'ordering': ('-created',), 'verbose_name': '피드백 대화방', 'verbose_name_plural': '피드백 대화방'},
        ),
        migrations.RemoveIndex(
            model_name='feedbackcomment',
            name='feedbacks_f_parent__421613_idx',
        ),
        migrations.RemoveIndex(
            model_name='feedbackcomment',
            name='feedbacks_f_is_impo_891fef_idx',
        ),
        migrations.RemoveField(
            model_name='feedbackcomment',
            name='is_important',
        ),
        migrations.RemoveField(
            model_name='feedbackcomment',
            name='parent',
        ),
        migrations.AddField(
            model_name='feedbackmessage',
            name='status',
            field=models.CharField(choices=[('pending', '대기중'), ('completed', '완료')], default='pending', help_text='피드백 메시지 처리 상태', max_length=20, verbose_name='상태'),
        ),
        migrations.AddIndex(
            model_name='feedbackmessage',
            index=models.Index(fields=['feedback', '-created'], name='feedbacks_f_feedbac_73a730_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackmessage',
            index=models.Index(fields=['user'], name='feedbacks_f_user_id_d8eb97_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackmessage',
            index=models.Index(fields=['status'], name='feedbacks_f_status_aea527_idx'),
        ),
        migrations.DeleteModel(
            name='FeedbackReaction',
        ),
        migrations.DeleteModel(
            name='GuestFeedbackSession',
        ),
    ]
