[phases.setup]
nixPkgs = ['nodejs', 'python39', 'yarn']

[phases.install]
cmds = [
    'cd vridge_front && npm install',
    'cd vridge_back && pip install -r requirements.txt'
]

[phases.build]
cmds = [
    'cd vridge_front && npm run build',
    'cd vridge_back && python manage.py collectstatic --noinput --settings=config.settings.railway'
]

[start]
cmd = 'cd vridge_back && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT'