# Generated by Django 4.2.7 on 2025-07-02 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0013_alter_basicplan_end_date_alter_basicplan_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(db_index=True, max_length=255)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('request_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='processing', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '멱등성 레코드',
                'verbose_name_plural': '멱등성 레코드',
                'indexes': [models.Index(fields=['created_at'], name='projects_id_created_fdbd79_idx')],
                'unique_together': {('user', 'idempotency_key')},
            },
        ),
    ]
