[phases.setup]
nixPkgs = ["python311", "gcc", "python311Packages.pip"]

[phases.install]
cmds = ["python3 -m pip install --upgrade pip", "python3 -m pip install -r requirements.txt"]

[start]
cmd = "python3 simple_server.py"