[build]
builder = "NIXPACKS"
nixpacksPlan = """
[phases.setup]
nixPkgs = ["python311", "ffmpeg", "postgresql"]

[phases.install]
cmds = ["pip install -r requirements.txt"]
"""

[deploy]
startCommand = "python manage.py migrate --settings=config.settings.railway && python manage.py collectstatic --noinput --settings=config.settings.railway && gunicorn config.wsgi:application --bind 0.0.0.0:${PORT:-8000} --timeout 300"
restartPolicyType = "always"
healthcheckPath = "/health/"
healthcheckTimeout = 300

[[services]]
name = "web"