[build]
  base = "vridge_front"
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_BASE_URL = "https://vridge-back-production.up.railway.app"
  REACT_APP_BACKEND_API_URL = "https://vridge-back-production.up.railway.app"
  REACT_APP_BACKEND_URI = "https://vridge-back-production.up.railway.app"
  REACT_APP_SOCKET_URI = "wss://vridge-back-production.up.railway.app"
  GENERATE_SOURCEMAP = "false"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200